### ISSUE TITLE
"pwgen -n 1" doesn't work as advertised

### ISSUE THREAD

**Issue by robatino** [jbernard/pwgen#2]
I originally reported this at https://bugzilla.redhat.com/show_bug.cgi?id=1462557 against pwgen-2.07-4.fc26.x86_64 in Fedora Rawhide. The issue is that "pwgen -n 1" does not produce 1-character numeric passwords, as the man page claims. I have not tested this against the upstream version, but the behavior is likely the same. Please close if it isn't, or if this is the wrong upstream bug tracker to report this. Thanks.

**Comment by jbernard** [comment]
This repository is a mirror, I created it a while back because the upstream site was not responding.  So the bug should be directed to wherever active upstream development is occurring (if that's happening).

That aside, I suspect the issue you'll encounter is that passwords of length 1 are not particularly useful, and so the time to fix this bug would not yield enough value to justify working on it.  But that's just my suspension, you are correct that the behaviour as documented is wrong.
